/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DAO.Session;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class LoginFrame extends JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setLocationRelativeTo(null);
        pack();
        txtPassword.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        logoCircle = new javax.swing.JPanel();
        lblLogoIcon = new javax.swing.JLabel();
        lblAppName = new javax.swing.JLabel();
        lblAppSub = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        lblConnexion = new javax.swing.JLabel();
        lblConnexionSub = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SmartCaisse - Connexion");
        setPreferredSize(new java.awt.Dimension(420, 520));

        topPanel.setBackground(new java.awt.Color(219, 234, 254));
        topPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 0, 24, 0));
        topPanel.setPreferredSize(new java.awt.Dimension(0, 160));
        topPanel.setLayout(new javax.swing.BoxLayout(topPanel, javax.swing.BoxLayout.Y_AXIS));

        logoCircle.setBackground(new java.awt.Color(255, 255, 255));
        logoCircle.setMaximumSize(new java.awt.Dimension(56, 56));
        logoCircle.setPreferredSize(new java.awt.Dimension(56, 56));

        lblLogoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hand-shake.png"))); // NOI18N
        lblLogoIcon.setPreferredSize(new java.awt.Dimension(28, 28));
        logoCircle.add(lblLogoIcon);

        topPanel.add(logoCircle);

        lblAppName.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblAppName.setForeground(new java.awt.Color(14, 165, 233));
        lblAppName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppName.setText("SmartCaisse");
        lblAppName.setAlignmentX(0.5F);
        topPanel.add(lblAppName);

        lblAppSub.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblAppSub.setForeground(new java.awt.Color(59, 130, 246));
        lblAppSub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppSub.setText("Gestion Microfinance");
        lblAppSub.setAlignmentX(0.5F);
        topPanel.add(lblAppSub);

        getContentPane().add(topPanel, java.awt.BorderLayout.NORTH);

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 32, 32, 32));
        centerPanel.setLayout(new javax.swing.BoxLayout(centerPanel, javax.swing.BoxLayout.Y_AXIS));

        lblConnexion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblConnexion.setForeground(new java.awt.Color(15, 23, 42));
        lblConnexion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConnexion.setText("Connexion");
        lblConnexion.setAlignmentX(0.5F);
        lblConnexion.setMaximumSize(new java.awt.Dimension(9999, 30));
        centerPanel.add(lblConnexion);

        lblConnexionSub.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblConnexionSub.setForeground(new java.awt.Color(100, 116, 139));
        lblConnexionSub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConnexionSub.setText("Entrez vos identifiants pour accéder");
        lblConnexionSub.setAlignmentX(0.5F);
        lblConnexionSub.setMaximumSize(new java.awt.Dimension(9999, 25));
        centerPanel.add(lblConnexionSub);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(9999, 20));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        centerPanel.add(jPanel1);

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(71, 85, 105));
        lblUsername.setText("Nom d'utilisateur");
        lblUsername.setAlignmentX(0.5F);
        lblUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 4, 0));
        lblUsername.setMaximumSize(new java.awt.Dimension(9999, 20));
        centerPanel.add(lblUsername);

        txtUsername.setMaximumSize(new java.awt.Dimension(9999, 40));
        txtUsername.setPreferredSize(new java.awt.Dimension(0, 40));
        centerPanel.add(txtUsername);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(9999, 14));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 14));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        centerPanel.add(jPanel2);

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(71, 85, 105));
        lblPassword.setText("Mot de passe");
        lblPassword.setAlignmentX(0.5F);
        lblPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 4, 0));
        lblPassword.setMaximumSize(new java.awt.Dimension(9999, 20));
        centerPanel.add(lblPassword);

        txtPassword.setText("jPasswordField1");
        txtPassword.setMaximumSize(new java.awt.Dimension(9999, 40));
        txtPassword.setPreferredSize(new java.awt.Dimension(0, 40));
        centerPanel.add(txtPassword);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(9999, 20));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 20));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        centerPanel.add(jPanel3);

        btnLogin.setBackground(new java.awt.Color(14, 165, 233));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Se connecter");
        btnLogin.setAlignmentX(0.5F);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setMaximumSize(new java.awt.Dimension(9999, 44));
        btnLogin.setPreferredSize(new java.awt.Dimension(0, 44));
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        centerPanel.add(btnLogin);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText().trim();
    String password = new String(txtPassword.getPassword()).trim();
    
    // Vérification champs vides
    if (username.isEmpty() || password.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Veuillez remplir tous les champs !",
            "Champs manquants",
            javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }
    
    // Vérification en base
    DAO.UtilisateurDAO dao = new DAO.UtilisateurDAO();
    Models.Utilisateur user = dao.connecter(username, password);
    
    if (user != null) {
        // Stocker l'utilisateur en session
        Session.setUtilisateur(user);
        // Ouvrir MainFrame
        new Mainframe().setVisible(true);
        // Fermer le login
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(
            this,
            "Identifiants incorrects !",
            "Erreur de connexion",
            JOptionPane.ERROR_MESSAGE
                
        );
        txtPassword.setText("");
    }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
    com.formdev.flatlaf.FlatLightLaf.setup();
    System.setProperty("flatlaf.disableMigLayoutIntegration", "true");
    java.awt.EventQueue.invokeLater(() -> {
        new LoginFrame().setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAppName;
    private javax.swing.JLabel lblAppSub;
    private javax.swing.JLabel lblConnexion;
    private javax.swing.JLabel lblConnexionSub;
    private javax.swing.JLabel lblLogoIcon;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel logoCircle;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
