/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DAO.PretDAO;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.BorderFactory;
import javax.swing.SwingUtilities;

/**
 *
 * @author Admin
 */
public class Mainframe extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Mainframe.class.getName());

    /**
     * Creates new form Mainframe
     */
    private DashboardPanel dashboardPanel = new DashboardPanel();

    public Mainframe() {
        initComponents();
        // Mise à jour des statuts au démarrage
        new PretDAO().mettreAJourStatuts();
        this.setPreferredSize(new java.awt.Dimension(800, 600));
        pack();
        setLocation(100, 50);
        setMinimumSize(new java.awt.Dimension(800, 600));

        // Ajouter les vues dans le CardLayout
        ClientsPanel clients = new ClientsPanel();
        ComptePanel epargne = new ComptePanel();
        PretsPanel prets = new PretsPanel();
        TransactionsPanel transactions = new TransactionsPanel();

        contentPanel.add(dashboardPanel, "dashboard");
        contentPanel.add(clients, "clients");
        contentPanel.add(prets, "prets");
        contentPanel.add(transactions, "transactions");
        contentPanel.add(epargne, "epargne");
        RapportsPanel rapports = new RapportsPanel();
        contentPanel.add(rapports, "rapports");

        // Afficher le dashboard par défaut
        java.awt.CardLayout cl = (java.awt.CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "dashboard");
        dashboardPanel.chargerDonnees(); // ← charger au démarrage

        // Navigation boutons
        btnDashboard.addActionListener(e -> showPanel("dashboard"));
        btnClients.addActionListener(e -> showPanel("clients"));
        btnEpargne.addActionListener(e -> showPanel("epargne"));
        btnPrets.addActionListener(e -> showPanel("prets"));
        btnTransactions.addActionListener(e -> showPanel("transactions"));
        btnRapports.addActionListener(e -> showPanel("rapports"));

    }

    private void showPanel(String panel) {
        // Changer la vue dans CardLayout
        java.awt.CardLayout cl = (java.awt.CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, panel);

        // Bouton actif
        javax.swing.JButton[] btns = {btnDashboard, btnClients, btnPrets, btnTransactions, btnEpargne, btnRapports};
        for (javax.swing.JButton b : btns) {
            b.setBackground(new java.awt.Color(15, 23, 42));
            b.setForeground(new java.awt.Color(203, 213, 225));
            b.setBorder(BorderFactory.createEmptyBorder(0, 16, 0, 0));
        }

        // Colorer le bouton actif
        javax.swing.JButton actif = switch (panel) {
            case "dashboard" ->
                btnDashboard;
            case "clients" ->
                btnClients;
            case "epargne" ->
                btnEpargne;
            case "prets" ->
                btnPrets;
            case "transactions" ->
                btnTransactions;
            case "rapports" ->
                btnRapports;
            default ->
                btnDashboard;
        };
        actif.setBackground(new java.awt.Color(30, 41, 59));
        actif.setForeground(new java.awt.Color(14, 165, 233));
        actif.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0,
                        new java.awt.Color(14, 165, 233)),
                javax.swing.BorderFactory.createEmptyBorder(0, 13, 0, 0)
        ));

        // Charger les données si Dashboard
        if ("dashboard".equals(panel)) {
            dashboardPanel.chargerDonnees();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        txtPanel = new javax.swing.JPanel();
        lblAppName = new javax.swing.JLabel();
        lblSousTitre = new javax.swing.JLabel();
        navPanel = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnClients = new javax.swing.JButton();
        btnEpargne = new javax.swing.JButton();
        btnPrets = new javax.swing.JButton();
        btnTransactions = new javax.swing.JButton();
        btnRapports = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        sidebarPanel.setBackground(new java.awt.Color(15, 23, 42));
        sidebarPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(226, 232, 240)));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(200, 0));
        sidebarPanel.setLayout(new javax.swing.BoxLayout(sidebarPanel, javax.swing.BoxLayout.Y_AXIS));

        logoPanel.setBackground(new java.awt.Color(15, 23, 42));
        logoPanel.setAlignmentX(0.0F);
        logoPanel.setMaximumSize(new java.awt.Dimension(220, 70));
        logoPanel.setPreferredSize(new java.awt.Dimension(220, 70));
        logoPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblIcon.setForeground(new java.awt.Color(255, 255, 255));
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/house.png"))); // NOI18N
        logoPanel.add(lblIcon);

        txtPanel.setBackground(new java.awt.Color(15, 23, 42));
        txtPanel.setLayout(new javax.swing.BoxLayout(txtPanel, javax.swing.BoxLayout.Y_AXIS));

        lblAppName.setBackground(new java.awt.Color(15, 23, 42));
        lblAppName.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblAppName.setForeground(java.awt.Color.white);
        lblAppName.setText("SmartCaisse");
        txtPanel.add(lblAppName);

        lblSousTitre.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblSousTitre.setForeground(new java.awt.Color(100, 116, 139));
        lblSousTitre.setText("Microfinance");
        txtPanel.add(lblSousTitre);

        logoPanel.add(txtPanel);

        sidebarPanel.add(logoPanel);

        navPanel.setBackground(new java.awt.Color(15, 23, 42));
        navPanel.setMaximumSize(new java.awt.Dimension(220, 300));
        navPanel.setPreferredSize(new java.awt.Dimension(220, 300));
        navPanel.setLayout(new javax.swing.BoxLayout(navPanel, javax.swing.BoxLayout.Y_AXIS));

        btnDashboard.setBackground(new java.awt.Color(15, 23, 42));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(203, 213, 225));
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashboard.png"))); // NOI18N
        btnDashboard.setText("Tableau de bord");
        btnDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.setFocusPainted(false);
        btnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard.setMaximumSize(new java.awt.Dimension(220, 45));
        btnDashboard.setPreferredSize(new java.awt.Dimension(220, 45));
        navPanel.add(btnDashboard);

        btnClients.setBackground(new java.awt.Color(13, 23, 42));
        btnClients.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnClients.setForeground(new java.awt.Color(203, 213, 225));
        btnClients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        btnClients.setText("Clients");
        btnClients.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        btnClients.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClients.setFocusPainted(false);
        btnClients.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnClients.setMaximumSize(new java.awt.Dimension(220, 45));
        btnClients.setPreferredSize(new java.awt.Dimension(220, 45));
        navPanel.add(btnClients);

        btnEpargne.setBackground(new java.awt.Color(15, 23, 42));
        btnEpargne.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnEpargne.setForeground(new java.awt.Color(203, 213, 225));
        btnEpargne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/wallet.png"))); // NOI18N
        btnEpargne.setText("Compte");
        btnEpargne.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        btnEpargne.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEpargne.setFocusPainted(false);
        btnEpargne.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEpargne.setMaximumSize(new java.awt.Dimension(220, 45));
        btnEpargne.setPreferredSize(new java.awt.Dimension(220, 45));
        navPanel.add(btnEpargne);

        btnPrets.setBackground(new java.awt.Color(15, 23, 42));
        btnPrets.setForeground(new java.awt.Color(203, 213, 225));
        btnPrets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/payment.png"))); // NOI18N
        btnPrets.setText("Prêts");
        btnPrets.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        btnPrets.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrets.setFocusPainted(false);
        btnPrets.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPrets.setMaximumSize(new java.awt.Dimension(220, 45));
        btnPrets.setPreferredSize(new java.awt.Dimension(220, 45));
        navPanel.add(btnPrets);

        btnTransactions.setBackground(new java.awt.Color(15, 23, 42));
        btnTransactions.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnTransactions.setForeground(new java.awt.Color(203, 213, 225));
        btnTransactions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/swap.png"))); // NOI18N
        btnTransactions.setText("Transactions");
        btnTransactions.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        btnTransactions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransactions.setFocusPainted(false);
        btnTransactions.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTransactions.setMaximumSize(new java.awt.Dimension(220, 45));
        btnTransactions.setPreferredSize(new java.awt.Dimension(220, 45));
        navPanel.add(btnTransactions);

        btnRapports.setBackground(new java.awt.Color(15, 23, 42));
        btnRapports.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnRapports.setForeground(new java.awt.Color(203, 213, 225));
        btnRapports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bar-chart.png"))); // NOI18N
        btnRapports.setText("Rapports");
        btnRapports.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        btnRapports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRapports.setFocusPainted(false);
        btnRapports.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRapports.setMaximumSize(new java.awt.Dimension(220, 45));
        btnRapports.setPreferredSize(new java.awt.Dimension(220, 45));
        navPanel.add(btnRapports);

        sidebarPanel.add(navPanel);

        getContentPane().add(sidebarPanel, java.awt.BorderLayout.WEST);

        contentPanel.setBackground(new java.awt.Color(248, 250, 252));
        contentPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        com.formdev.flatlaf.FlatLightLaf.setup();
        System.setProperty("flatlaf.disableMigLayoutIntegration", "true");
        java.awt.EventQueue.invokeLater(() -> {
            new LoginFrame().setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClients;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnEpargne;
    private javax.swing.JButton btnPrets;
    private javax.swing.JButton btnRapports;
    private javax.swing.JButton btnTransactions;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel lblAppName;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblSousTitre;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel navPanel;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JPanel txtPanel;
    // End of variables declaration//GEN-END:variables
}
